version: '3'

services:
  mongo:
    image: mongo:4.1.10
    command: mongod
    ports:
      - "27017:27017"
    networks:
      - infra

  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongo:27017/users
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - infra

networks:
  infra:
    driver: bridge
